  // Mock data
  export const drivers = [
    {
      id: "1234",
      name: "John Smith",
      vehicle: "TR-442",
      isActive: true,
      fatigueScore: 87,
      trend: "rising",
      duration: "11h 30m",
      sleepHours: 4.5,
      drowsiness: 91,
      alertness: 23,
      heartRate: 92,
      location: "Highway 95N"
    },
    {
      id: "5678",
      name: "Sarah Johnson",
      vehicle: "TR-118",
      isActive: true,
      fatigueScore: 89,
      trend: "rising",
      duration: "9h 45m",
      sleepHours: 5.2,
      drowsiness: 85,
      alertness: 18,
      heartRate: 88,
      location: "I-80 East"
    },
    {
      id: "9012",
      name: "Mike Brown",
      vehicle: "TR-225",
      isActive: false,
      fatigueScore: 45,
      lastActive: "2h 15m ago",
      sleepHours: 7.5,
      location: "Rest Stop A"
    },
    {
      id: "3456",
      name: "Lisa Chen",
      vehicle: "TR-331",
      isActive: true,
      fatigueScore: 72,
      trend: "rising",
      duration: "8h 20m",
      sleepHours: 6.8,
      drowsiness: 68,
      alertness: 42,
      heartRate: 78,
      location: "Route 66"
    },
    {
      id: "7890",
      name: "David Martinez",
      vehicle: "TR-567",
      isActive: true,
      fatigueScore: 45,
      trend: "stable",
      duration: "5h 10m",
      sleepHours: 8.0,
      drowsiness: 32,
      alertness: 78,
      heartRate: 72,
      location: "Highway 101"
    },
    {
      id: "2345",
      name: "Emily Wilson",
      vehicle: "TR-892",
      isActive: true,
      fatigueScore: 56,
      trend: "stable",
      duration: "6h 40m",
      sleepHours: 7.2,
      drowsiness: 45,
      alertness: 65,
      heartRate: 75,
      location: "I-95 South"
    },
    {
      id: "6789",
      name: "Robert Taylor",
      vehicle: "TR-123",
      isActive: false,
      fatigueScore: 38,
      lastActive: "45m ago",
      sleepHours: 7.8,
      location: "Depot B"
    },
    {
      id: "4567",
      name: "Jennifer Lee",
      vehicle: "TR-445",
      isActive: true,
      fatigueScore: 78,
      trend: "rising",
      duration: "10h 15m",
      sleepHours: 5.5,
      drowsiness: 75,
      alertness: 35,
      heartRate: 85,
      location: "Highway 40"
    },
  ];
